### ISSUE TITLE
First Coordinate group is sometimes set to [0.0, 0.0]

### ISSUE THREAD

**Issue by soulsplit** [urschrei/polyline-ffi#1] opened 2018-05-29 09:35 UTC
## Description of the issue
I'm using the polyline library through pypolyline module in python3. When encoding a series of coordinates and decoding the polyline afterwards again I noticed that it is sometimes wrongly represented. It seems to be happening during the encoding step as also the encoded polyline string changes when encoding the same series of coordinates in this case.
The first coordinate group is set to [0.0, 0.0] and all following coordinates will be wrong as they just represent a modification of the predecessors.

## Example
**Input coordinates:**
[[52.48803, 13.37053], [52.48941, 13.37067], [52.49048, 13.37073], [52.49072, 13.37078], [52.49267, 13.37093], [52.49158, 13.37628], [52.49153, 13.37638], [52.49148, 13.37659], [52.49148, 13.37659], [52.49169, 13.37758], [52.49224, 13.37934], [52.49335, 13.38273], [52.49352, 13.38349], [52.49516, 13.38402], [52.49849, 13.38521], [52.49755, 13.38921], [52.49746, 13.38986], [52.49739, 13.39063], [52.49737, 13.39139], [52.4974, 13.39203], [52.49742, 13.39278], [52.49761, 13.39486], [52.49781, 13.3956], [52.49793, 13.39586], [52.49812, 13.39593], [52.49837, 13.39594], [52.49877, 13.39584], [52.499, 13.39574], [52.50068, 13.39474], [52.50094, 13.39461], [52.50141, 13.39448], [52.50165, 13.39448], [52.50186, 13.39451], [52.5022, 13.39463], [52.50246, 13.39478], [52.50283, 13.39508], [52.50319, 13.39543], [52.50355, 13.39571], [52.50533, 13.39703], [52.5055, 13.39712], [52.50585, 13.39734], [52.50616, 13.39757], [52.50635, 13.39775], [52.50708, 13.39829], [52.5073, 13.39842], [52.50754, 13.39859], [52.50819, 13.3991], [52.5095, 13.40001], [52.50968, 13.40019], [52.51031, 13.40099], [52.51056, 13.40126], [52.51065, 13.40131], [52.51082, 13.40134], [52.51101, 13.40131], [52.51122, 13.40126], [52.51125, 13.40142], [52.51135, 13.40173], [52.51137, 13.4018], [52.5116, 13.40231], [52.51215, 13.40318], [52.51319, 13.40468], [52.51402, 13.40582], [52.51534, 13.40746], [52.51576, 13.40796], [52.51653, 13.40894], [52.5168, 13.40927], [52.51819, 13.41087], [52.51858, 13.41141], [52.51899, 13.41215], [52.51915, 13.41236], [52.51927, 13.41256], [52.52009, 13.41429], [52.52021, 13.4145], [52.52033, 13.41468], [52.52087, 13.41532], [52.52194, 13.41641], [52.52341, 13.41802], [52.52366, 13.41832], [52.52398, 13.4188], [52.52498, 13.41996], [52.52522, 13.42022], [52.52593, 13.41848]]

**Encoded and then decoded coordinates:**
[**[0.0, 0.0]**, [-53750.25664, 13.37073], [-53750.2564, 13.37078], [-53750.25445, 13.37093], [-53750.25554, 13.37628], [-53750.25559, 13.37638], [-53750.25564, 13.37659], [-53750.25564, 13.37659], [-53750.25543, 13.37758], [-53750.25488, 13.37934], [-53750.25377, 13.38273], [-53750.2536, 13.38349], [-53750.25196, 13.38402], [-53750.24863, 13.38521], [-53750.24957, 13.38921], [-53750.24966, 13.38986], [-53750.24973, 13.39063], [-53750.24975, 13.39139], [-53750.24972, 13.39203], [-53750.2497, 13.39278], [-53750.24951, 13.39486], [-53750.24931, 13.3956], [-53750.24919, 13.39586], [-53750.249, 13.39593], [-53750.24875, 13.39594], [-53750.24835, 13.39584], [-53750.24812, 13.39574], [-53750.24644, 13.39474], [-53750.24618, 13.39461], [-53750.24571, 13.39448], [-53750.24547, 13.39448], [-53750.24526, 13.39451], [-53750.24492, 13.39463], [-53750.24466, 13.39478], [-53750.24429, 13.39508], [-53750.24393, 13.39543], [-53750.24357, 13.39571], [-53750.24179, 13.39703], [-53750.24162, 13.39712], [-53750.24127, 13.39734], [-53750.24096, 13.39757], [-53750.24077, 13.39775], [-53750.24004, 13.39829], [-53750.23982, 13.39842], [-53750.23958, 13.39859], [-53750.23893, 13.3991], [-53750.23762, 13.40001], [-53750.23744, 13.40019], [-53750.23681, 13.40099], [-53750.23656, 13.40126], [-53750.23647, 13.40131], [-53750.2363, 13.40134], [-53750.23611, 13.40131], [-53750.2359, 13.40126], [-53750.23587, 13.40142], [-53750.23577, 13.40173], [-53750.23575, 13.4018], [-53750.23552, 13.40231], [-53750.23497, 13.40318], [-53750.23393, 13.40468], [-53750.2331, 13.40582], [-53750.23178, 13.40746], [-53750.23136, 13.40796], [-53750.23059, 13.40894], [-53750.23032, 13.40927], [-53750.22893, 13.41087], [-53750.22854, 13.41141], [-53750.22813, 13.41215], [-53750.22797, 13.41236], [-53750.22785, 13.41256], [-53750.22703, 13.41429], [-53750.22691, 13.4145], [-53750.22679, 13.41468], [-53750.22625, 13.41532], [-53750.22518, 13.41641], [-53750.22371, 13.41802], [-53750.22346, 13.41832], [-53750.22314, 13.4188], [-53750.22214, 13.41996], [-53750.2219, 13.42022], [-53750.22119, 13.41848]]

## Expected
A given set of coordinates should always yield the same encoded polyline.

**Comment by urschrei** [comment] 2018-05-29 13:45
[Looks](https://travis-ci.org/urschrei/pypolyline/builds/385193780) like this is occurring on Linux, but not macOS. Perplexing.

**Comment by soulsplit** [comment] 2018-05-29 15:19
My observations are that this is random behavior, so may be running the new test 10 times will also make macOS fail at least once.

**Comment by urschrei** [comment] 2018-05-29 15:26
I've just modified the test to loop 10k times, and it doesn't fail on macOS. Hmm.

**Comment by urschrei** [comment] 2018-05-30 13:07
This is fixed in v0.1.13, released to PyPI. (Caused by premature GC that arises when casting numpy arrays to pointers). It wasn't caught by tests because it only arises in sequences > 63 elements.

**Closed as completed by urschrei** 2018-05-30 13:07 UTC
